repos:
- repo: https://github.com/timothycrosley/isort
  rev: 5.8.0
  hooks:
   - id: isort
     args: ["--profile", "black"]
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
    types: [python]
    exclude: docs/
    args:
      - -S
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: double-quote-string-fixer
    - id: check-merge-conflict
    - id: fix-encoding-pragma
      args: ["--remove"]
    - id: mixed-line-ending
      args: ["--fix=lf"]
